spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true